apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-szmezrux
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-szmezrux:98e7887bdf769780d096fa4c4c115140c86ed506@sha256:8a95a14c41aba063299e2cb54afc71d139a91d93c49b9f193c6a85b40292d65a
        name: container-image  
